# Generated by Django 2.0.3 on 2018-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180508_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
