# Generated by Django 2.0.3 on 2018-05-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180520_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read_count',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Read_Count',
        ),
    ]
