# Generated by Django 2.0.3 on 2018-07-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='LikeCount',
        ),
    ]
