# Generated by Django 2.0.3 on 2018-07-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time']},
        ),
    ]
